### ISSUE TITLE
CI: problems building on netlify

### ISSUE THREAD

**Issue by rossbar** [rossbar/github_graphql#10]
It looks like there is now a [dependency conflict on netlify](https://app.netlify.com/sites/devstats/deploys/62008879ccb6a1c4e72c780d) that is preventing the site from building. I'm not seeing this locally, I expect the issue is either environment caching on netlify's side or some problem with Python 3.8 (or both). Things I've tried:
 - Rerunning the netlify deply with the "clear cache and deploy" option
 - Rerunning netlify deploy with `--no-cache-dir` for the pip install
 - Updating to Python 3.9 or 3.10 in the netlify.toml (it doesn't seem netlify supports either)

**Comment by jarrodmillman** [comment]
I will take a look.

**Comment by rossbar** [comment]
I suspect (hope) that virtualenv would solve the issue, but I don't know how many commands you can chain together in the netlify build command. I've also added the data as a submodule now so the command to setup and build everything would look something like:

```
python -m venv devstats-venv
source devstats-venv/bin/activate
python -m pip install -r requirements.txt -r site/requirements.txt
git submodule update --init
make -C site/ html
```
