### ISSUE TITLE
BUG: Off by 1 error in Pony factor calculation and logarithmic plotting

### ISSUE THREAD

**Issue by lagru** [rossbar/github_graphql#36]
I think there are one or two errors with how the pony factor is calculated and displayed.

https://github.com/scientific-python/devstats.scientific-python.org/blob/d11ed47225f12222d707541f6d2088b81b009b0a/analysis_template.md?plain=1#L574-L591

It basically boils down to 0 being the first index. First `numpy.searchsorted` determines an index `N` for where the threshold should be inserted. The way I understand this is that we need to add 1 to this index as the Pony factor constitutes the majority > 50% of all PRs. 

Secondly, `ax.plot(np.cumsum(num_merged_prs_per_author), ".") ` creates an automatic index starting with 0. However, because the x axis uses the log scale, the first value at 0 is never shown!

E.g. in scikit-image's case, the largest number of merged PRs by one author is 271 which isn't shown and

```python
cummulative_prs = np.cumsum(num_merged_prs_per_author)[:10]
threshold = num_merged_prs * pf_thresh
pony_factor = np.searchsorted(
    np.cumsum(num_merged_prs_per_author), num_merged_prs * pf_thresh
)
print(f"{cummulative_prs=}\n{threshold=}\n{pony_factor=}")  # prints
# cummulative_prs=array([ 271,  496,  719,  913, 1085, 1252, 1367, 1471, 1569, 1662])
# threshold=1449.5
# pony_factor=7
```
I'd say in this case the Pony factor should be 8 and not 7 like returned by `searchsorted`.

**Comment by rossbar** [comment]
Nice catch @lagru , I agree with your assessment both on the pony factor and the visualization. Please feel free to submit a PR to fix this up. If not, I'll aim to fix it in the near future.

**Comment by lagru** [comment]
I'm currently traveling. But I'm happy to do a PR if this is still open by the time I get back.
